config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, path: 'admins', controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations', passwords: 'admins/passwords'}
  namespace :admins, path: 'quan-ly' do
    root to: "home#index"
    resources :services, path: 'dich-vu'
    resources :users, path: 'nguoi-dung'
    resources :messages, path: 'tin-nhan'
    resources :blogs, path: 'bai-viet'
  end

  root to: "home#index"
  get 'gioi-thieu', to: "home#introduces"
  get 'lien-he', to: "home#contact"
  resources :services, path: 'dich-vu'
  resources :messages, path: 'tin-nhan'
  resources :blogs, path: 'bai-viet'
  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap
  get 'robots.:format' => 'sitemap#robots'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/views/layouts/admin/_footer.html.erb
<div class="copy_layout">
  <p>Copyright © 2020. All Rights Reserved </p>
</div>

app/views/layouts/admin/_header.html.erb
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <%= link_to 'Dashboard', admins_root_path, class: 'navbar-brand' %>
</div>
<!-- /.navbar-header -->
<ul class="nav navbar-nav navbar-right">
<!--     <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-comments-o"></i><span class="badge"><%= @messages.count %></span></a>
        <ul class="dropdown-menu">
            <li class="dropdown-menu-header">
                <strong>Tin nhắn</strong>
            </li>
            <% @messages.each do |msg| %>
                <li class="avatar">
                    <a href="#">
                        <%= image_tag('admins/1.png', alt: 'dien lanh long an') %>
                        <div>New message</div>
                        <small>1 minute ago</small>
                        <span class="label label-info">NEW</span>
                    </a>
                </li>
            <% end %>
            <li class="dropdown-menu-footer text-center">
                <a href="#">View all messages</a>
            </li>
        </ul>
    </li> -->
    <li class="dropdown">
        <%= link_to admins_user_path(current_user.slug), class: 'dropdown-toggle avatar', data: { toggle: 'dropdown'} do %>
            <% if current_user.avatar.attached? %>
                <%= image_tag(current_user.avatar, alt: 'dien lanh long an') %>
            <% else %>
                <%= image_tag('admins/1.png', alt: 'dien lanh long an') %>
            <% end %>
        <% end %>

        <ul class="dropdown-menu">
            <li class="dropdown-menu-header text-center">
                <strong>Cài đặt</strong>
            </li>
            <li class="m_2"><%= link_to admins_user_path(current_user.slug) do %>
                <i class="fa fa-user"></i>Thông tin cá nhân
                <% end %>
            </li>
            <li class="m_2"><%= link_to edit_admins_user_path(current_user.slug) do %>
                <i class="fa fa-wrench"></i>Chỉnh sửa
                <% end %>
            </li>
            <li class="m_2"><%= link_to destroy_user_session_path, method: 'DELETE' do %>
                <i class="fa fa-lock"></i>Đăng xuất
                <% end %>
            </li>
        </ul>
    </li>
</ul>

app/views/layouts/admin/_menu.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <%= link_to admins_users_path do %>
                    <i class='fa fa-users fa-fw nav_icon'></i>
                     Quản lý admin
                <% end %>
            </li>
            <li>
                <%= link_to admins_services_path do %>
                    <i class='fa fa-dashboard fa-fw nav_icon'></i>
                    Quản lý dịch vụ
                <% end %>
            </li>
            <li>
                <%= link_to admins_messages_path do %>
                    <i class="fa fa-comments fa-fw nav_icon"></i>
                    Tin nhắn
                <% end %>
            </li>
            <li>
                <%= link_to admins_blogs_path do %>
                    <i class="fa fa-rss-square nav_icon"></i>
                    Bài viết
                <% end %>
            </li>
        </ul>
    </div>
</div>