config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, path: 'admins', controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations', passwords: 'admins/passwords'}
  namespace :admins, path: 'quan-ly' do
    root to: "home#index"
    resources :services, path: 'dich-vu'
    resources :users, path: 'nguoi-dung'
    resources :messages, path: 'tin-nhan'
    resources :blogs, path: 'bai-viet'
  end

  root to: "home#index"
  get 'gioi-thieu', to: "home#introduces"
  get 'lien-he', to: "home#contact"
  resources :services, path: 'dich-vu'
  resources :messages, path: 'tin-nhan'
  resources :blogs, path: 'bai-viet'
  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap
  get 'robots.:format' => 'sitemap#robots'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :email, presence: true, length: { in: 5..100 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name, presence: true
  validates :phone, uniqueness: true,
                    numericality: true,
                    length: { minimum: 10, maximum: 15 },
                    allow_blank: true
  before_save :translate_slug
  has_one_attached :avatar
  default_scope { order(created_at: :desc) }

  def password_required?
    new_record? ? super : false
  end

  def translate_slug
    self.slug = format_string_with_unsigned(self.name)
  end
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < ApplicationController
    before_action :find_user, only: [:edit, :update, :destroy, :show]
    def index
      @users  = User.all.page(params[:page]).per(10)
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admins_users_path, notice: 'Đã tạo thành công'
      else
        render :new
      end
    end

    def edit
    end

    def show
    end

    def update
      if @user.update(user_params)
        redirect_to admins_users_path, notice: 'Cập nhật thành công'
      else
        render :edit, notice: 'Cập nhật thất bại'
      end
    end

    def destroy
      if @user.destroy
        redirect_to admins_users_path, notice: 'Xóa thành công'
      else
        redirect_to admins_users_path, notice: 'Xóa thất bại'
      end
    end

    private
    def user_params
      params.require(:user).permit(:name, :email, :password, :phone, :gender, :avatar)
    end

    def find_user
      @user = User.friendly.find(params[:id])
    end
  end
end

app/views/admins/users/_form.html.erb
<%= form_for @user, :url => (@user.new_record? ? admins_users_url : admins_user_url(@user)), html: { class: 'form-horizontal'} do |f| %>
    <% if @user.errors.any? %>
        <ul class="alert.alert-danger">
            <% @user.errors.full_messages.uniq.each do |message| %>
                <div style="color: red">
                    <%= message %>
                </div>
            <% end %>
        </ul>
    <% end %>
    <div class="form-group">
        <label for="focusedinput" class="col-sm-2 control-label">Tên <span style="color: red">*</span></label>
        <div class="col-sm-8">
         <%= f.text_field :name, class: 'form-control1', id: 'focusedinput', placeholder: 'Tên' %>
        </div>
    </div>
    <div class="form-group">
        <label for="disabledinput" class="col-sm-2 control-label">Email <span style="color: red">*</span></label>
        <div class="col-sm-8">
            <%= f.text_field :email, class: 'form-control1', id: 'disabledinput', placeholder: 'Email' %>
        </div>
    </div>
    <div class="form-group">
        <label for="phone" class="col-sm-2 control-label">Số điện thoại</label>
        <div class="col-sm-8">
         <%= f.text_field :phone, class: 'form-control1', id: 'phone', placeholder: 'Số điện thoại' %>
        </div>
    </div>
    <div class="form-group">
        <label for="inputPassword" class="col-sm-2 control-label">Mật Khẩu</label>
        <div class="col-sm-8">
            <%= f.password_field :password, class: 'form-control1', id: 'inputPassword', placeholder: 'Mật khẩu' %>
        </div>
    </div>
    <div class="form-group">
        <label for="radio" class="col-sm-2 control-label">Giới tính</label>
        <div class="col-sm-8">
            <div class="radio-inline"><label>
                <%= f.radio_button :gender, true, checked: true  %>
                Nam
            </div>
            <div class="radio-inline"><label>
                <%= f.radio_button :gender, false %>
                Nữ
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="txtarea1" class="col-sm-2 control-label">Địa chỉ</label>
        <div class="col-sm-8">
            <%= f.text_area :address, class: 'form-control1', id: 'txtarea1', cols: "50", rows: "4" %>
        </div>
    </div>
    <div class="form-group">
        <label for="avatar" class="col-sm-2 control-label">Ảnh đại diện</label>
        <div class="col-sm-8">
            <%= f.file_field :avatar, class: 'form-control1', id: 'avatar'%>
        </div>
    </div>
    <div class="form-group" style="text-align: center">
      <% if @user.id.present? %>
            <button type="submit" class="btn btn_5 btn-lg btn-primary">Cập nhật</button>
      <% else %>
            <button type="submit" class="btn btn_5 btn-lg btn-primary">Tạo</button>
      <% end %>
    </div>
<% end %>

app/views/admins/users/edit.html.erb
<div id="page-wrapper">
    <div class="col-md-12 graphs">
        <div class="xs">
            <h3>Chỉnh sửa Người quản lý</h3>
            <div class="bs-example4" data-example-id="contextual-table">
                <%= render 'form' %>
            </div>
        </div>
        <%= render 'layouts/admin/footer' %>
    </div>
</div>

app/views/admins/users/index.html.erb
<div id="page-wrapper">
    <div class="col-md-12 graphs">
        <div class="xs">
            <h3>Danh sách người quản lý</h3>
            <div class="bs-example4" data-example-id="contextual-table">
                <div>
                  <% flash.each do |type, msg| %>
                    <div class="alert alert-info">
                      <%= msg %>
                    </div>
                  <% end %>
                </div>
                <div>
                  <%=link_to new_admins_user_path, class: 'btn btn-primary pull-right' do %>
                    <i class="fa fa-plus-circle" aria-hidden="true">Thêm mới</i>
                  <% end %>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th width="5%">ID</th>
                            <th width="10%">Tên</th>
                            <th width="20%">Email</th>
                            <th width="30%">Ngày Tạo</th>
                            <th width="25%">Hành động </th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @users.each_with_index do |user, index| %>
                        <tr class="active">
                            <th scope="row"><%= user.id %></th>
                            <td><%= user.name %></td>
                            <td><%= user.email %></td>
                            <td><%= format_date(user.created_at) %></td>
                            <td>
                              <%= link_to edit_admins_user_path(user.slug), class: 'btn btn-xs btn-info' do %>
                                <i class="fa fa-pencil-square-o" aria-hidden="true">Chỉnh sửa</i>
                              <% end %>
                              <%= link_to admins_user_path(user.slug), class: 'btn btn-xs btn-warning warning_44' do %>
                                <i class="fa fa-eye" aria-hidden="true">Chi tiết</i>
                              <% end %>
                              <%= link_to admins_user_path(user.slug), method: :delete, data: { confirm: 'Bạn có muốn xóa?' }, class: 'btn btn-xs btn-success warning_4' do %>
                                <i class="fa fa-trash-o" aria-hidden="true">Xóa</i>
                              <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
            <div>
                <%= paginate @users, theme: 'twitter-bootstrap-3' %>
            </div>
        </div>
        <%= render 'layouts/admin/footer' %>
    </div>
</div>

app/views/admins/users/new.html.erb
<div id="page-wrapper">
    <div class="col-md-12 graphs">
        <div class="xs">
            <h3>Tạo Người quản lý mới</h3>
            <div class="bs-example4" data-example-id="contextual-table">
                <%= render 'form' %>
            </div>
        </div>
        <%= render 'layouts/admin/footer' %>
    </div>
</div>

app/views/admins/users/show.html.erb
<div id="page-wrapper">
    <div class="col-md-12 graphs">
        <div class="xs">
            <h3>Chi tiết người quản lý</h3>
            <div class="bs-example4" data-example-id="contextual-table">
              <div>Tên: <%= @user.name %></div>
              <div>Email: <%= @user.email %></div>
              <div>Địa chỉ: <%= @user.address %></div>
              <div>Giới Tính: <%= @user.gender == true ? 'Nam' : 'Nữ' %></div>
              <div>Ngày tạo: <%= format_date(@user.created_at) %></div>
            </div>
        </div>
        <%= render 'layouts/admin/footer' %>
    </div>
</div>