config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, path: 'admins', controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations', passwords: 'admins/passwords'}
  namespace :admins, path: 'quan-ly' do
    root to: "home#index"
    resources :services, path: 'dich-vu'
    resources :users, path: 'nguoi-dung'
    resources :messages, path: 'tin-nhan'
    resources :blogs, path: 'bai-viet'
  end

  root to: "home#index"
  get 'gioi-thieu', to: "home#introduces"
  get 'lien-he', to: "home#contact"
  resources :services, path: 'dich-vu'
  resources :messages, path: 'tin-nhan'
  resources :blogs, path: 'bai-viet'
  get "/sitemap.xml" => "sitemap#index", :format => "xml", :as => :sitemap
  get 'robots.:format' => 'sitemap#robots'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :email, presence: true, length: { in: 5..100 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name, presence: true
  validates :phone, uniqueness: true,
                    numericality: true,
                    length: { minimum: 10, maximum: 15 },
                    allow_blank: true
  before_save :translate_slug
  has_one_attached :avatar
  default_scope { order(created_at: :desc) }

  def password_required?
    new_record? ? super : false
  end

  def translate_slug
    self.slug = format_string_with_unsigned(self.name)
  end
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < ApplicationController
    before_action :find_user, only: [:edit, :update, :destroy, :show]
    def index
      @users  = User.all.page(params[:page]).per(10)
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admins_users_path, notice: 'Đã tạo thành công'
      else
        render :new
      end
    end

    def edit
    end

    def show
    end

    def update
      if @user.update(user_params)
        redirect_to admins_users_path, notice: 'Cập nhật thành công'
      else
        render :edit, notice: 'Cập nhật thất bại'
      end
    end

    def destroy
      if @user.destroy
        redirect_to admins_users_path, notice: 'Xóa thành công'
      else
        redirect_to admins_users_path, notice: 'Xóa thất bại'
      end
    end

    private
    def user_params
      params.require(:user).permit(:name, :email, :password, :phone, :gender, :avatar)
    end

    def find_user
      @user = User.friendly.find(params[:id])
    end
  end
end

app/views/layouts/user/_footer.html.erb
<footer class="footer-area">
    <div class="footer-top pt--50 pb--100">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="footer-info mt--60">
                        <div class="logo">
                            <a href="#">
                                <%= image_tag('logo/logo-2.png', alt: 'dien lanh long an') %>
                            </a>
                        </div>
                        <p>Điện lạnh Nguyễn Trắng - Long An chuyên sửa chữa máy lạnh, điều hòa , tủ lạnh, uy tín chất lượng chuyên nghiệp</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer-info  mt--60">
                        <div class="footer-title">
                            <h3>Từ khóa nổi bật</h3>
                        </div>
                        <ul class="footer-list">
                            <li>Sửa chữa điện lạnh</li>
                            <li>Sửa chữa tủ lạnh</li>
                            <li>Sửa chữa máy lạnh</li>
                            <li>Sửa chữa máy giặt</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="footer-info  mt--60">
                        <div class="footer-title">
                            <h3>Facebook</h3>
                        </div>
                        <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2F%25C4%2590i%25E1%25BB%2587n-l%25E1%25BA%25A1nh-Nguy%25E1%25BB%2585n-Tr%25E1%25BA%25AFng-101814951459021%2F%3Fmodal%3Dadmin_todo_tour&tabs=timeline&width=340&height=222&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=638039330096614" width="340" height="222" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6">
                    <div class="footer-info  mt--60">
                        <div class="footer-title">
                            <h3>Liên hệ </h3>
                        </div>
                        <ul class="footer-list">
                            <li>Ấp 1, Mỹ Phú, Thủ Thừa, Long An</li>
                            <li>Số điện thoại: 0793750267 - 0944159707</li>
                            <li>Email: trangnguyen14041985@gmail.com </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-bottom-inner text-center">
                        <p>Copyright &copy;  2020 All Right Reserved</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/user/_header.html.erb
    <!-- header-area start -->
    <div class="header-area">

        <!-- header-top start -->
        <div class="header-top pt--20 pb--20">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-3 col-12">
                        <!-- logo start -->
                        <div class="logo">
                            <%= link_to root_path do %>
                                <%= image_tag('logo/logo.png',alt: 'dien lanh long an', style: 'height: 85px; width: 200px') %>
                            <% end %>
                        </div>
                        <!-- logo End -->
                    </div>
                    <div class="col-lg-8 col-md-9 col-12">
                        <!-- Contact-information-top Start -->
                        <div class="contact-information-top">

                            <!-- Single-information-top Start -->
                            <div class="single-information-top">
                                <div class="info-icon">
                                    <i class="icofont-headphone-alt-2"></i>
                                </div>
                                <div class="info-content">
                                    <h4 class='abcdef'>Hotline</h4>
                                    <p>0793750267 - 0944159707</p>
                                </div>
                            </div>
                            <!-- Single-information-top End -->

                            <!-- Single-information-top Start -->
                            <div class="single-information-top">
                                <div class="info-icon">
                                    <i class="icofont-clock-time"></i>
                                </div>
                                <div class="info-content">
                                    <h4>Thứ 2 - Chủ Nhật</h4>
                                    <p>7.00 am - 5.00 pm</p>
                                </div>
                            </div>
                            <!-- Single-information-top End -->

                        </div>
                        <!-- Contact-information-top End -->
                    </div>
                </div>
            </div>
        </div>
        <!-- header-top end -->
        <%= render 'layouts/user/menu' %>
    </div>
    <!-- header-area end -->

app/views/layouts/user/_menu.html.erb
        <!-- header-bottom-area Start -->
        <div class="header-bottom-area header-sticky">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="header-menu-wrap border-top-1">
                            <!-- main-menu-area Start -->
                            <div class="main-menu">
                                <nav class="main-navigation">
                                    <ul>
                                        <li class="active"><%= link_to 'TRANG CHỦ', root_path %></li>
                                        <li><%= link_to 'GIỚI THIỆU', gioi_thieu_path %></li>
                                        <li><%= link_to 'DỊCH VỤ', services_path %>
                                            <ul class="sub-menu">
                                                <% @services.each do |service| %>
                                                    <li>
                                                        <%= link_to service.name, service_path(service.slug) %>
                                                    </li>
                                                <% end %>
                                            </ul>
                                        </li>
                                        <li><%= link_to 'BÀI VIẾT', blogs_path %>
                                            <ul class="sub-menu">
                                                <% @blogs.each do |blog| %>
                                                    <li>
                                                        <%= link_to blog.title, blog_path(blog.slug) %>
                                                    </li>
                                                <% end %>
                                            </ul>
                                        </li>
                                        <li><%= link_to 'LIÊN HỆ', lien_he_path %></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <!-- mobile-menu start -->
                        <div class="mobile-menu d-block d-lg-none"></div>
                        <!-- mobile-menu end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- header-bottom-area End -->